### ISSUE TITLE
[FEAT] Add a unified endpoint to manage systemctl services

### ISSUE THREAD

**Issue by shabhilash** [shabhilash/homeops-api#1]
### Description: 
Create a single API endpoint to manage systemctl services, including starting, stopping, restarting, reloading, enabling, and disabling services. This will provide a unified interface for controlling services dynamically via API calls.

### Details:

**_Endpoint:_** /service
**_Method:_** POST
**_Query Parameters:_**

`service` _(string, required)_: The name of the service to manage.
`action` _(string, required)_: The action to perform, one of start, stop, restart, reload, enable, or disable.

### Example Request:

```
POST /service?service=nginx&action=start
POST /service?service=nginx&action=stop
POST /service?service=nginx&action=restart
POST /service?service=nginx&action=reload
POST /service?service=nginx&action=enable
POST /service?service=nginx&action=disable
```
### Response:

Success message indicating the action performed.
Error message if the action fails.

### Tasks:

- [x]  Create the `/service` endpoint.
- [x]  Parse the service and action parameters.
- [ ]  Implement logic for each action (`start, stop, restart, reload, enable, disable`).
- [ ]  Return appropriate success or error messages.
- [ ]  Write unit tests for the endpoint.
