### ISSUE TITLE
[FEAT] Add an endpoint to check the status of systemctl services

### ISSUE THREAD

**Issue by shabhilash** [shabhilash/homeops-api#2]
### Description: 
Develop an API endpoint to retrieve the status of systemctl services. This endpoint will allow users to check whether a service is active, inactive, or in any other state.

### Details:

**Endpoint**: `/service/status`
**Method**: GET
**Query Parameters:**
`service` _(string, required)_: The name of the service to check.

### Example Request:

GET /service/status?service=nginx

### Response:

JSON object with the status of the service.

### Example:
```
{
  "service": "nginx",
  "status": "active"
}
```

### Tasks:

- [x] Create the /service endpoint.
- [x]  Parse the service parameter.
- [ ]  Implement logic to execute systemctl status {service}.
- [ ]  Parse the output to determine the service status.
- [ ]  Return the service status in JSON format.
- [ ]  Write unit tests for the endpoint.
