### ISSUE TITLE
[FEAT] Add an endpoint to fetch logs of systemctl services

### ISSUE THREAD

**Issue by shabhilash** [shabhilash/homeops-api#3]
### Description: 
Develop an API endpoint to fetch the logs of systemctl services. This will allow users to view the logs for debugging and monitoring purposes.

### Details:

**Endpoint**: `/service/logs`
**Method**: GET
**Query Parameters:**
`service` _(string, required)_: The name of the service to fetch logs for.
### Example Request:
`GET /service/logs?service=nginx`
### Response:

JSON object with the logs of the service.
### Example:
```
{
  "service": "nginx",
  "logs": "..."
}
```
### Tasks:

- [ ]  Create the `/service/logs` endpoint.
- [ ]  Parse the service parameter.
- [ ]  Implement logic to execute` journalctl -u {service}`.
- [ ]  Return the service logs in JSON format.
- [ ]  Write unit tests for the endpoint.
