### ISSUE TITLE
[FEAT] Add an endpoint to monitor disk usage

### ISSUE THREAD

**Issue by shabhilash** [shabhilash/homeops-api#4]
### Description:
Create an API endpoint that returns the disk usage statistics of the system. This can help in monitoring the storage and taking action before running out of space.

### Details:
- **Endpoint:** `/stats/disk-usage`
- **Method:** `GET`
- **Response:**
  ```json
  {
      "total": "500GB",
      "used": "300GB",
      "free": "200GB",
      "percent_used": "60%"
  }

### Tasks:

- [ ]  Implement the `/stats/disk-usage` endpoint.
- [ ]  Fetch and return the disk usage statistics.
- [ ]  Write tests for the new endpoint.
