### ISSUE TITLE
[FEAT] Add an endpoint to monitor CPU and memory usage

### ISSUE THREAD

**Issue by shabhilash** [shabhilash/homeops-api#5]
### **Description:**
Create an API endpoint to fetch the current CPU and memory usage of the system. This will help in tracking system performance and identifying potential issues.

### **Details:**
- **Endpoint:** `/stats/system`
- **Method:** `GET`
- **Response:**
  ```json
  {
      "cpu_usage": "45%",
      "memory_usage": {
          "total": "16GB",
          "used": "8GB",
          "free": "8GB",
          "percent_used": "50%"
      }
  }
### Tasks:

- [ ]  Implement the `/stats/system` endpoint.
- [x]  Fetch and return CPU and memory usage statistics.
- [ ]  Write tests for the new endpoint.
